### ISSUE TITLE
Fix link to european standards f90

### ISSUE THREAD

**Issue by MattEdwards94** [BristolCompositesInstitute/RSE-Guide#4]
A new working link: https://wiki.c2sm.ethz.ch/pub/CM/CodingAdvicesCosmo2/europ_sd.pdf

**Comment by LKedward** [comment]
Closing since new up-to-date guidelines have now been added:
https://bristolcompositesinstitute.github.io/RSE-Guide/abaqus-user-subroutines/fortran-style-guidelines.html
