### ISSUE TITLE
Add a getting started with HPC guide (Particularly Abaqus)

### ISSUE THREAD

**Issue by MattEdwards94** [BristolCompositesInstitute/RSE-Guide#5]
A place to signpost new starters to. 

Include links to the ACRC HPC and Linux training
Explain how to get an account - i.e. the need for a project code and who to talk to to obtain one. 

Have a section specifically for Abaqus which explains e.g. how to load Abaqus, which versions are available where, the need to test small models first, and signposting the Abaqus Teams channel

**Comment by LKedward** [comment]
Status tracking:
- [x] Add Abaqus specific HPC documentation: hosted with HPC-Community docs (https://acrc.github.io/HPC-community-docs/engineering/abaqus/index.html)
- [x] Add page to RSE-Guide with link to HPC-Community docs and to ACRC docs

**Comment by LKedward** [comment]
Added link to HPC community docs in 6a3389bff797fb8a8b7ac0388b8e141d57af5de4
